### ISSUE TITLE
incompatibility between nerd-icons-completion and latest Melpa version of marginalia

### ISSUE THREAD

**Issue by maxecharel** [rainstormstudio/nerd-icons-completion#11]
Hi,

After having upgraded marginalia to its latest Melpa version (20240708.2158), icons disappeared from minibuffer completion.
I've filled an issue on marginalia's issue tracker (https://github.com/minad/marginalia/issues/175) , and @minad suggested that `nerd-icons-completion` would require an update following a recent commit to marginalia: https://github.com/minad/marginalia/commit/f2ac221aba25a8eeb5d0d607b8cca2d01998689f

Doable on your side?

Many thanks for your work!

Best,
M

**Comment by tralph3** [comment]
Also experiencing this issue.

**Comment by milanglacier** [comment]
Confirm with the same issue
