### ISSUE TITLE
Submitting to melpa?

### ISSUE THREAD

**Issue by milanglacier** [rainstormstudio/nerd-icons-completion#2]
Hi! This package works really well and I don't have any bug with it as of now. Do you consider submit it to melpa?
Since nerd-icons, nerd-icons-dired, and nerd-icons-ibuffer are already on melpa. With this package on melpa, the ecosystem will be amplified a lot again.

**Comment by rainstormstudio** [comment]
Sure. The thing is I personally do not use the default completion or vertico related packages so I didn't test this package. Since you think this is good enough I'll put it on Melpa then.
