### ISSUE TITLE
Load conflict with marginalia

### ISSUE THREAD

**Issue by orangecza** [rainstormstudio/nerd-icons-completion#4]
If `nerd-icons-completion` is loaded before `marginalia`, it won't function normally. Maybe their `advise-add` are conflict.
(I temporarily defer its load as a workaroud as below.)
```elisp
(use-package nerd-icons-completion
  :defer 1
  :after marginalia                     ;Temporarily conflict workaround
  :config
  (nerd-icons-completion-mode t))
```

**Comment by ChauhanT** [comment]
I am also encountering this problem. Even the `:defer` workaround doesn't work for me. The only thing that works is turning the `nerd-icons-completion-mode` on and off.

**Comment by websick-dev** [comment]
I had the same problem. The workaround below is the only one that worked for me:

```
(use-package nerd-icons-completion
  :hook (marginalia-mode . nerd-icons-completion-mode))
```

**Comment by rainstormstudio** [comment]
#3
