### ISSUE TITLE
No icons when calling `projectile-find-file`

### ISSUE THREAD

**Issue by bricka** [rainstormstudio/nerd-icons-completion#7]
When calling `find-file`, I get to see the icons. Awesome!

I use Projectile for project management, and when I call `projectile-find-file`, I sadly don't see icons for the files. 😭 Here's a screenshot:
<img width="571" alt="Screenshot 2023-07-13 at 16 10 15" src="https://github.com/rainstormstudio/nerd-icons-completion/assets/318395/6b9f6da8-7f49-4638-86a4-5decdc6b8ee6">

I would love to have icons here as well. Is this something that you're considering working on? Alternatively, I'm more than happy to try my hand at implementing it and putting up an MR, if you could give me some ideas about where to start. I'm not super familiar with the completion metadata logic in Emacs, so I found it a bit tough to figure out how to get started.

Thank you!

**Comment by rainstormstudio** [comment]
I haven't looked into this but it might be related to how projectile use completing-read

**Comment by rainstormstudio** [comment]
the default project.el does have icons shown so I'm guessing this is more projectile specific

**Comment by bricka** [comment]
Thanks for the hint! By looking into project.el, I'm pretty sure I see what's happening.

This package uses the completion category for determining that we're looking at candidates of category `project-file`, and then decides that we should do a file icon lookup for it. `project.el` sets the category here: https://github.com/emacs-mirror/emacs/blob/master/lisp/progmodes/project.el#L314-L320

I'm going to see if Projectile does anything similar with categories that we could maybe use.

**Comment by bricka** [comment]
There is an old issue against Projectile for this: https://github.com/bbatsov/projectile/issues/1664

It's fair to say that this is definitely a problem for Projectile. I might try one of the suggested workarounds there for now :). Thanks for the cool package!
